apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-alpine
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  source:
    path: helm
    repoURL: "https://github.com/rajugeorge/argo-test"
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
